version: "2.2"
services:
  demo:
    image: demo:1.1
    container_name: demo
    ports:
      - "8080:8080"
    environment:
      - REDIS_URIS=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./data:/data
    hostname: redis
    ports:
      - "6379:6379"
networks:
  default:
    external:
      name: demo-network
